name: GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      PICO_SDK_PATH: /home/runner/work/sample_rm_pico_app/sample_rm_pico_app/lib/pico-sdk
      SDK_VERSION: 1.5.0
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up the toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake doxygen gcc-arm-none-eabi  # libnewlib-arm-none-eabi build-essential
    #     with:
    #       submodules: true  # Fetch Hugo themes (true OR recursive)
    #       fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    #   - name: Setup Hugo
    #     uses: peaceiris/actions-hugo@v2
    #     with:
    #       hugo-version: '0.110.0'

    #   - name: Build
    #     run: hugo --minify
      - name: Set up the Pi Pico SDK
        run: |
          cd ${{ github.workspace }}
          pwd
          git submodule update --init
          cd rm_pico_dev
          git submodule update --init --recommend-shallow 
          cd lib/pico-sdk/
          git submodule update --init --recommend-shallow
      - name: Build
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake ..
          cd ..
          cmake --build ./build --target docs
      - name: debug #TODO remove
        run: |
          cd ${{ github.workspace }}
          ls
          echo ==
          pwd
          echo ==
          ls build
          echo ==
          ls build/rm_pico_dev/docs/html
          echo ==
          cd build/rm_pico_dev/docs/html
          pwd
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/build/rm_pico_dev/docs/html # ./build/rm_pico_dev/docs/html