name: GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      PICO_SDK_PATH: /home/runner/work/sample_rm_pico_app/lib/pico-sdk
      SDK_VERSION: 1.5.0
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up the toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential doxygen
    #     with:
    #       submodules: true  # Fetch Hugo themes (true OR recursive)
    #       fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    #   - name: Setup Hugo
    #     uses: peaceiris/actions-hugo@v2
    #     with:
    #       hugo-version: '0.110.0'

    #   - name: Build
    #     run: hugo --minify
      - name: Build
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake ..
          cmake --build . --target docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/rm_pico_dev/docs/html